import Joi from "joi";

// CREATE / UPDATE (POST /party)
export const createPartySchema = Joi.object({
  CityID: Joi.number().integer().allow(null, "").optional(),
  xCityID: Joi.number().integer().allow(null, "").optional(),
  PinCodeID: Joi.number().integer().allow(null, "").optional(),
  xPinCodeID: Joi.number().integer().allow(null, "").optional(),
  PinCode: Joi.number().integer().allow(null, "").optional(),
  ParentID: Joi.number().integer().allow(null, "").optional(),
  Balance: Joi.number().integer().allow(null, "").optional(),
  EmailStatusID: Joi.number().integer().allow(null, "").optional(),
  xPinCode: Joi.number().integer().allow(null, "").optional(),
  AreaID: Joi.number().integer().allow(null, "").optional(),
  xAreaID: Joi.number().integer().allow(null, "").optional(),
  DealerID: Joi.number().integer().required(),
  DesignationID: Joi.number().integer().allow(null, "").optional(),
  PartyGroupID: Joi.number().integer().allow(null, "").optional(),
  DOB: Joi.date().allow(null, "").optional(),
  DOJ: Joi.date().allow(null, "").optional(),
  OldDOJ: Joi.date().allow(null, "").optional(),
  DOA: Joi.date().allow(null, "").optional(),
  EmailDate: Joi.date().allow(null, "").optional(),
  IsActive: Joi.boolean().allow(null, "").optional(),
  BlackListed: Joi.boolean().allow(null, "").optional(),
  IsTeamViewer: Joi.boolean().allow(null, "").optional(),
  IsPrint: Joi.boolean().allow(null, "").optional(),
  IsSuspend: Joi.boolean().allow(null, "").optional(),
  IsCDSend: Joi.boolean().allow(null, "").optional(),
  IsTemp: Joi.boolean().allow(null, "").optional(),
  BouncingEmail: Joi.boolean().allow(null, "").optional(),
  PartyName: Joi.string().max(50).required(),
  FirmName: Joi.string().max(50).allow(null, "").optional(),
  Address1: Joi.string().max(50).allow(null, "").optional(),
  Address2: Joi.string().max(50).allow(null, "").optional(),
  Address3: Joi.string().max(50).allow(null, "").optional(),
  Address4: Joi.string().max(50).allow(null, "").optional(),
  FellYR: Joi.string().max(10).allow(null, "").optional(),
  SuspendReason: Joi.string().max(50).allow(null, "").optional(),
  History3: Joi.string().max(50).allow(null, "").optional(),
  TeamViewerID: Joi.string().max(15).allow(null, "").optional(),
  MRN: Joi.string().max(6).allow(null, "").optional(),
  AF: Joi.string().max(3).allow(null, "").optional(),
  CP: Joi.string().max(6).allow(null, "").optional(),
  AssoYR: Joi.string().max(10).allow(null, "").optional(),
  Phone3: Joi.string().max(50).allow(null, "").optional(),
  Fax1: Joi.string().max(50).allow(null, "").optional(),
  Fax2: Joi.string().max(50).allow(null, "").optional(),
  BlackListedProduct: Joi.string().max(50).allow(null, "").optional(),
  History1: Joi.string().max(50).allow(null, "").optional(),
  History2: Joi.string().max(50).allow(null, "").optional(),
  Mobile1: Joi.string().max(10).allow(null, "").optional(),
  Mobile2: Joi.string().max(10).allow(null, "").optional(),
  Mobile3: Joi.string().max(10).allow(null, "").optional(),
  Mobile4: Joi.string().max(10).allow(null, "").optional(),
  Phone1: Joi.string().max(50).allow(null, "").optional(),
  Phone2: Joi.string().max(50).allow(null, "").optional(),
  PhoneNo: Joi.string().max(50).allow(null, "").optional(),
  FaxNo: Joi.string().max(50).allow(null, "").optional(),
  Email1: Joi.string().max(50).allow(null, "").optional(),
  Email2: Joi.string().max(50).allow(null, "").optional(),
  VisitingHours: Joi.string().max(50).allow(null, "").optional(),
  CustomerPassword: Joi.string().max(25).allow(null, "").optional(),
  ShortName: Joi.string().max(3).allow(null, "").optional(),
  CustomerID: Joi.string().max(10).allow(null, "").optional(),
  SingleMulti: Joi.string().max(1).allow(null, "").optional(),
  IsProspective: Joi.boolean().allow(null, "").optional(),
  TeamViewerID1: Joi.string().max(15).allow(null, "").optional(),
  TeamViewerID2: Joi.string().max(15).allow(null, "").optional(),
  EmailStatus: Joi.number().integer().allow(null, "").optional(),
  IsSelect: Joi.boolean().allow(null, "").optional(),
  KYC: Joi.boolean().allow(null, "").optional(),
  temp2: Joi.number().integer().allow(null, "").optional(),
  KS_CoverDate: Joi.date().allow(null, "").optional(),
  KS_DocDate: Joi.date().allow(null, "").optional(),
  KS_SendDate: Joi.date().allow(null, "").optional(),
  KS_IsSend: Joi.boolean().allow(null, "").optional(),
  KS_IsCover: Joi.boolean().allow(null, "").optional(),
  KS_IsDoc: Joi.boolean().allow(null, "").optional(),
  KS_DocNo: Joi.string().max(20).allow(null, "").optional(),
  KS_DocMode: Joi.string().max(1).allow(null, "").optional(),
  xIsCall: Joi.number().integer().allow(null, "").optional(),
  xIsOver: Joi.number().integer().allow(null, "").optional(),
  xUserID: Joi.number().integer().allow(null, "").optional(),
  xCallDate: Joi.date().allow(null, "").optional(),
  xRemark2: Joi.string().max(100).allow(null, "").optional(),
  xRemark3: Joi.string().max(100).allow(null, "").optional(),
  xRemark4: Joi.string().max(100).allow(null, "").optional(),
  xRemark5: Joi.string().max(100).allow(null, "").optional(),
  xRemark1: Joi.string().max(100).allow(null, "").optional(),
  ReEmail: Joi.boolean().allow(null, "").optional(),
  BlockMode: Joi.boolean().allow(null, "").optional(),
  GSTNo: Joi.string().max(20).allow(null, "").optional(),
  ReferencePartyID: Joi.number().integer().allow(null, "").optional(),
  LeadGenerationID: Joi.number().integer().allow(null, "").optional(),
  Cguid: Joi.string().max(200).allow(null, "").optional(),
  flag: Joi.string()
    .valid("A", "U")
    .required()
    .messages({
      "any.only": "flag can be A or U only",
      "any.required": "flag is required",
    }),
});

// DELETE (DELETE /party)
export const deletePartySchema = Joi.object({
  CustomerID: Joi.string().required(),
  Cguid: Joi.string().required(),
});
