import { dbConection } from "../config/db.js";
import { sendBulkEmails } from "../services/email.js";

// CREATE / UPDATE VacancyApply
export const createVacancyApply = async (req, res) => {
  const {
    UkeyId = "", Name = "", Mobile = "", Email = "", UserName = req.user?.UserName || "System", flag = "A", vacencyMastUkeyId = ''
  } = req.body;

  const sequelize = await dbConection();

  try {
    const IpAddress = req?.headers["x-forwarded-for"] || req?.socket?.remoteAddress || "Not Found";

    let query = "";

    if (flag === "U") {
      query += `
        DELETE FROM VacancyApply WHERE UkeyId = :UkeyId;
      `;
    }

    query += `
      INSERT INTO VacancyApply
      (UkeyId, Name, Mobile, Email, IpAddress, EntryDate, UserName, flag, vacencyMastUkeyId)
      VALUES
      (:UkeyId, :Name, :Mobile, :Email, :IpAddress, GETDATE(), :UserName, :flag, :vacencyMastUkeyId);
    `;

    await sequelize.query(query, {
      replacements: {
        UkeyId, Name, Mobile, Email, IpAddress, UserName, flag, vacencyMastUkeyId
      },
    });

    const [vacancyResult] = await sequelize.query(
      `SELECT Title FROM VacancyMast WHERE VacancyUkeyId = :vacencyMastUkeyId`,
      { replacements: { vacencyMastUkeyId } }
    );

    const VacancyTitle = vacancyResult?.[0]?.Title || "N/A";
    console.log(vacancyResult);
    console.log('VacancyTitle :>> ', VacancyTitle);

    const emailHTML = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8" />
          <style>
            body {
              font-family: Arial, Helvetica, sans-serif;
              background-color: #f4f6f8;
              margin: 0;
              padding: 20px;
            }
            .container {
              max-width: 650px;
              margin: auto;
              background: #ffffff;
              border-radius: 6px;
              overflow: hidden;
              box-shadow: 0 2px 6px rgba(0,0,0,0.1);
            }
            .header {
              background: #0d6efd;
              color: #ffffff;
              padding: 15px 20px;
              font-size: 18px;
              font-weight: bold;
            }
            .content {
              padding: 20px;
              color: #333;
              font-size: 14px;
              line-height: 1.6;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 15px;
            }
            table td {
              padding: 8px;
              border-bottom: 1px solid #eee;
            }
            table td.label {
              font-weight: bold;
              width: 35%;
              background: #f8f9fa;
            }
            .footer {
              padding: 12px 20px;
              background: #f1f1f1;
              font-size: 12px;
              color: #666;
              text-align: center;
            }
            .note {
              margin-top: 15px;
              font-style: italic;
              color: #555;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">New Vacancy Application Received</div>
            <div class="content">
              <p>A New Application Has Been Submitted For The Position: <strong>${VacancyTitle}</strong>.<span> Please Review And Take Necessary Action.</span></p>
              <table>
                <tr>
                  <td class="label">Name:</td>
                  <td>${Name}</td>
                </tr>
                <tr>
                  <td class="label">Email:</td>
                  <td>${Email}</td>
                </tr>
                <tr>
                  <td class="label">Mobile:</td>
                  <td>${Mobile}</td>
                </tr>
              </table>
            </div>
            <div class="footer">
              This email was automatically generated by the recruitment system on ${new Date().toLocaleString()}.
            </div>
          </div>
        </body>
        </html>
    `;

    if(flag === 'A'){
      sendBulkEmails([{email : 'helpsurat@gmail.com'}], `New Application For Job`, emailHTML)
    }

    res.status(200).json({
      message: flag === "A" ? "Vacancy applied successfully" : "Vacancy application updated successfully",
      Success: true,
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message, Success: false });
  } finally {
    await sequelize.close();
  }
};

// GET VacancyApply (with filters + pagination)
export const getVacancyApply = async (req, res) => {
  const { UkeyId, Name, Email, Page, PageSize } = req.query;
  const sequelize = await dbConection();

  try {
    let query = `SELECT va.*, dm.FileName, vm.Title FROM VacancyApply va left join DocMast dm on dm.MasterUkeyId = va.UkeyId left join VacancyMast vm on vm.VacancyUkeyId = va.vacencyMastUkeyId WHERE 1=1`;
    let countQuery = `SELECT COUNT(*) as totalCount FROM VacancyApply va WHERE 1=1`;
    const replacements = {};

    if (UkeyId) {
      query += " AND va.UkeyId = :UkeyId";
      countQuery += " AND UkeyId = :UkeyId";
      replacements.UkeyId = UkeyId;
    }
    if (Name) {
      query += " AND va.Name LIKE :Name";
      countQuery += " AND Name LIKE :Name";
      replacements.Name = `%${Name}%`;
    }
    if (Email) {
      query += " AND va.Email LIKE :Email";
      countQuery += " AND Email LIKE :Email";
      replacements.Email = `%${Email}%`;
    }

    // Sort by latest entries first
    query += " ORDER BY EntryDate DESC";

    // Total count
    const [countResult] = await sequelize.query(countQuery, { replacements });
    const totalCount = countResult[0]?.totalCount || 0;

    // Pagination
    const pageNum = parseInt(Page, 10);
    const pageSizeNum = parseInt(PageSize, 10);

    if (!isNaN(pageNum) && !isNaN(pageSizeNum) && pageNum > 0 && pageSizeNum > 0) {
      const offset = (pageNum - 1) * pageSizeNum;
      query += " OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY";
      replacements.offset = offset;
      replacements.pageSize = pageSizeNum;
    }

    const [results] = await sequelize.query(query, { replacements });
    res.status(200).json({ data: results, totalCount, Success: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Database error", Success: false });
  } finally {
    await sequelize.close();
  }
};

// DELETE VacancyApply
export const deleteVacancyApply = async (req, res) => {
  const { UkeyId } = req.params;
  const sequelize = await dbConection();

  try {
    const query = "DELETE FROM VacancyApply WHERE UkeyId = :UkeyId";
    const result = await sequelize.query(query, { replacements: { UkeyId } });

    if (result[1] === 0) {
      return res.status(404).json({ error: "Vacancy application not found", Success: false });
    }

    res.status(200).json({ message: "Vacancy application deleted successfully", Success: true });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message, Success: false });
  } finally {
    await sequelize.close();
  }
};
