import { DataTypes } from "sequelize";
import sequelize from "../config/db.js";

const Dealer = sequelize.define(
  "Dealer",
  {
    DealerID: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    CityID: { type: DataTypes.INTEGER, allowNull: true },
    DesignationID: { type: DataTypes.INTEGER, allowNull: true },
    rCityID: { type: DataTypes.INTEGER, allowNull: true },
    DealerPartyID: { type: DataTypes.INTEGER, allowNull: true },
    DOB: { type: DataTypes.DATE, allowNull: true },
    DOJ: { type: DataTypes.DATE, allowNull: true },
    DOA: { type: DataTypes.DATE, allowNull: true },
    BlackListed: { type: DataTypes.BOOLEAN, allowNull: true },
    DealerName: { type: DataTypes.STRING(50), allowNull: false },
    Address1: { type: DataTypes.STRING(50), allowNull: true },
    Address2: { type: DataTypes.STRING(50), allowNull: true },
    Address3: { type: DataTypes.STRING(50), allowNull: true },
    Address4: { type: DataTypes.STRING(50), allowNull: true },
    MobileNo: { type: DataTypes.STRING(10), allowNull: true },
    rAddress3: { type: DataTypes.STRING(50), allowNull: true },
    rAddress4: { type: DataTypes.STRING(50), allowNull: true },
    rMobileNo: { type: DataTypes.STRING(50), allowNull: true },
    rPhoneNo: { type: DataTypes.STRING(50), allowNull: true },
    rFaxNo: { type: DataTypes.STRING(50), allowNull: true },
    PhoneNo: { type: DataTypes.STRING(50), allowNull: true },
    FirmName: { type: DataTypes.STRING(50), allowNull: true },
    FaxNo: { type: DataTypes.STRING(50), allowNull: true },
    Email: { type: DataTypes.STRING(50), allowNull: true },
    rAddress1: { type: DataTypes.STRING(50), allowNull: true },
    rAddress2: { type: DataTypes.STRING(50), allowNull: true },
    CustomerID: { type: DataTypes.CHAR(10), allowNull: true },
    DealerFileCode: { type: DataTypes.CHAR(3), allowNull: true },
    AcName: { type: DataTypes.STRING(50), allowNull: true },
    BankName: { type: DataTypes.STRING(50), allowNull: true },
    AcNo: { type: DataTypes.STRING(20), allowNull: true },
    IsActive: { type: DataTypes.BOOLEAN, allowNull: true },
    MobileNo2: { type: DataTypes.STRING(10), allowNull: true },
    MobileNo3: { type: DataTypes.STRING(10), allowNull: true },
    IsLocalDealer: { type: DataTypes.BOOLEAN, allowNull: true },
    IsST: { type: DataTypes.BOOLEAN, allowNull: true },
    FirmID: { type: DataTypes.INTEGER, allowNull: true },
    dTerms1: { type: DataTypes.STRING(100), allowNull: true },
    dTerms2: { type: DataTypes.STRING(100), allowNull: true },
    dTerms3: { type: DataTypes.STRING(100), allowNull: true },
    BillingFirmID: { type: DataTypes.INTEGER, allowNull: true },
    opening: { type: DataTypes.INTEGER, allowNull: true },
    IsPrint: { type: DataTypes.BOOLEAN, allowNull: true },
    IsIncludeST: { type: DataTypes.BOOLEAN, allowNull: true },
    GSTNo: { type: DataTypes.STRING(20), allowNull: true },
    BankId: { type: DataTypes.INTEGER, allowNull: true },
    CompanyEmail: { type: DataTypes.STRING(200), allowNull: true },
    Password: { type: DataTypes.STRING(100), allowNull: true },
    Flag: { type: DataTypes.STRING(2), allowNull: true },
    IpAddress: { type: DataTypes.STRING(200), allowNull: true },
    EntryDate: { type: DataTypes.DATE, allowNull: true },
    UserName: { type: DataTypes.STRING(100), allowNull: true },
  },
  {
    tableName: "Dealer",
    timestamps: false,
  }
);

export default Dealer;
