import { DataTypes } from "sequelize";
import { dbConection } from "../config/db.js";

const sequelize = await dbConection();

const Party = sequelize.define(
  "PartyMast",
  {
    PartyID: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
      autoIncrement: true, // Assuming auto-increment for primary key int
    },
    CityID: { type: DataTypes.INTEGER, allowNull: true },
    xCityID: { type: DataTypes.INTEGER, allowNull: true },
    PinCodeID: { type: DataTypes.INTEGER, allowNull: true },
    xPinCodeID: { type: DataTypes.INTEGER, allowNull: true },
    PinCode: { type: DataTypes.INTEGER, allowNull: true },
    ParentID: { type: DataTypes.INTEGER, allowNull: true },
    Balance: { type: DataTypes.INTEGER, allowNull: true },
    EmailStatusID: { type: DataTypes.INTEGER, allowNull: true },
    xPinCode: { type: DataTypes.INTEGER, allowNull: true },
    AreaID: { type: DataTypes.INTEGER, allowNull: true },
    xAreaID: { type: DataTypes.INTEGER, allowNull: true },
    DealerID: { type: DataTypes.INTEGER, allowNull: false },
    DesignationID: { type: DataTypes.INTEGER, allowNull: true },
    PartyGroupID: { type: DataTypes.INTEGER, allowNull: true },
    DOB: { type: DataTypes.DATE, allowNull: true },
    DOJ: { type: DataTypes.DATE, allowNull: true },
    OldDOJ: { type: DataTypes.DATE, allowNull: true },
    DOA: { type: DataTypes.DATE, allowNull: true },
    EmailDate: { type: DataTypes.DATE, allowNull: true },
    IsActive: { type: DataTypes.BOOLEAN, allowNull: true },
    BlackListed: { type: DataTypes.BOOLEAN, allowNull: true },
    IsTeamViewer: { type: DataTypes.BOOLEAN, allowNull: true },
    IsPrint: { type: DataTypes.BOOLEAN, allowNull: true },
    IsSuspend: { type: DataTypes.BOOLEAN, allowNull: true },
    IsCDSend: { type: DataTypes.BOOLEAN, allowNull: true },
    IsTemp: { type: DataTypes.BOOLEAN, allowNull: true },
    BouncingEmail: { type: DataTypes.BOOLEAN, allowNull: true },
    PartyName: { type: DataTypes.STRING(50), allowNull: false },
    FirmName: { type: DataTypes.STRING(50), allowNull: true },
    Address1: { type: DataTypes.STRING(50), allowNull: true },
    Address2: { type: DataTypes.STRING(50), allowNull: true },
    Address3: { type: DataTypes.STRING(50), allowNull: true },
    Address4: { type: DataTypes.STRING(50), allowNull: true },
    FellYR: { type: DataTypes.STRING(10), allowNull: true },
    SuspendReason: { type: DataTypes.STRING(50), allowNull: true },
    History3: { type: DataTypes.STRING(50), allowNull: true },
    TeamViewerID: { type: DataTypes.STRING(15), allowNull: true },
    MRN: { type: DataTypes.STRING(6), allowNull: true },
    AF: { type: DataTypes.STRING(3), allowNull: true },
    CP: { type: DataTypes.STRING(6), allowNull: true },
    AssoYR: { type: DataTypes.STRING(10), allowNull: true },
    Phone3: { type: DataTypes.STRING(50), allowNull: true },
    Fax1: { type: DataTypes.STRING(50), allowNull: true },
    Fax2: { type: DataTypes.STRING(50), allowNull: true },
    BlackListedProduct: { type: DataTypes.STRING(50), allowNull: true },
    History1: { type: DataTypes.STRING(50), allowNull: true },
    History2: { type: DataTypes.STRING(50), allowNull: true },
    Mobile1: { type: DataTypes.STRING(10), allowNull: true },
    Mobile2: { type: DataTypes.STRING(10), allowNull: true },
    Mobile3: { type: DataTypes.STRING(10), allowNull: true },
    Mobile4: { type: DataTypes.STRING(10), allowNull: true },
    Phone1: { type: DataTypes.STRING(50), allowNull: true },
    Phone2: { type: DataTypes.STRING(50), allowNull: true },
    PhoneNo: { type: DataTypes.STRING(50), allowNull: true },
    FaxNo: { type: DataTypes.STRING(50), allowNull: true },
    Email1: { type: DataTypes.STRING(50), allowNull: true },
    Email2: { type: DataTypes.STRING(50), allowNull: true },
    VisitingHours: { type: DataTypes.STRING(50), allowNull: true },
    CustomerPassword: { type: DataTypes.STRING(25), allowNull: true },
    ShortName: { type: DataTypes.CHAR(3), allowNull: true },
    CustomerID: { type: DataTypes.CHAR(10), allowNull: true },
    SingleMulti: { type: DataTypes.CHAR(1), allowNull: true },
    IsProspective: { type: DataTypes.BOOLEAN, allowNull: true },
    TeamViewerID1: { type: DataTypes.STRING(15), allowNull: true },
    TeamViewerID2: { type: DataTypes.STRING(15), allowNull: true },
    EmailStatus: { type: DataTypes.INTEGER, allowNull: true },
    IsSelect: { type: DataTypes.BOOLEAN, allowNull: true },
    KYC: { type: DataTypes.BOOLEAN, allowNull: true },
    temp2: { type: DataTypes.INTEGER, allowNull: true },
    KS_CoverDate: { type: DataTypes.DATE, allowNull: true },
    KS_DocDate: { type: DataTypes.DATE, allowNull: true },
    KS_SendDate: { type: DataTypes.DATE, allowNull: true },
    KS_IsSend: { type: DataTypes.BOOLEAN, allowNull: true },
    KS_IsCover: { type: DataTypes.BOOLEAN, allowNull: true },
    KS_IsDoc: { type: DataTypes.BOOLEAN, allowNull: true },
    KS_DocNo: { type: DataTypes.STRING(20), allowNull: true },
    KS_DocMode: { type: DataTypes.STRING(1), allowNull: true },
    xIsCall: { type: DataTypes.INTEGER, allowNull: true },
    xIsOver: { type: DataTypes.INTEGER, allowNull: true },
    xUserID: { type: DataTypes.INTEGER, allowNull: true },
    xCallDate: { type: DataTypes.DATE, allowNull: true },
    xRemark2: { type: DataTypes.STRING(100), allowNull: true },
    xRemark3: { type: DataTypes.STRING(100), allowNull: true },
    xRemark4: { type: DataTypes.STRING(100), allowNull: true },
    xRemark5: { type: DataTypes.STRING(100), allowNull: true },
    xRemark1: { type: DataTypes.STRING(100), allowNull: true },
    ReEmail: { type: DataTypes.BOOLEAN, allowNull: true },
    BlockMode: { type: DataTypes.BOOLEAN, allowNull: true },
    GSTNo: { type: DataTypes.STRING(20), allowNull: true },
    ReferencePartyID: { type: DataTypes.INTEGER, allowNull: true },
    LeadGenerationID: { type: DataTypes.INTEGER, allowNull: true },
    Cguid: { type: DataTypes.STRING(200), allowNull: true },
  },
  {
    tableName: "PartyMast",
    timestamps: false,
  }
);

export default Party;
